version: "3.9"

services:
  api:
    build: .
    container_name: invoice_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      STORAGE_BACKEND: "s3"
      AWS_DEFAULT_REGION: "eu-central-1"
      UPLOADS_PREFIX: "s3://3c-vetcostcheck/uploads"
      # optional but useful
      OUTPUT_PREFIX: "s3://3c-vetcostcheck/processed"
      REDIS_URL: "redis://redis:6379/0"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --log-level debug

  worker:
    build: .
    container_name: invoice_worker
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      STORAGE_BACKEND: "s3"
      AWS_DEFAULT_REGION: "eu-central-1"
      UPLOADS_PREFIX: "s3://3c-vetcostcheck/uploads"
      OUTPUT_PREFIX: "s3://3c-vetcostcheck/processed"
      REDIS_URL: "redis://redis:6379/0"
    command: python jobs/worker.py

  redis:
    image: redis:7
    container_name: invoice_redis
    # no need to expose externally for local compose networking
    # ports:
    #   - "6379:6379"